version: "3.8"

services:
  speech_to_text:
    build: ./services/speech_to_text
    ports:
      - "5001:5001"
    restart: always
    command: ["python", "app.py"]
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}

  summarizer:
    build: ./services/summarizer
    ports:
      - "5002:5002"
    restart: always
    command: ["python", "app.py"]
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}

  quiz_engine:
    build: ./services/quiz_engine
    ports:
      - "5003:5003"
    restart: always
    command: ["python", "app.py"]
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}

